name: TIL Summary

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Update README
      run: |
        echo "# Today I Learned" > README.md
        echo "" >> README.md
        echo "$(ls -1 *.md | wc -l) TILs so far." >> README.md
        echo "" >> README.md
        echo "Last updated on $(date)." >> README.md

    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -am "Update TIL summary" || exit 0
        git push
